### ISSUE TITLE
编译时遇到这样的警告信息

### ISSUE THREAD

**Issue by xiongzhaoxu** [abdallah-odeh/flutter_file_downloader#37] opened 2024-01-22 08:28 UTC
Building with Flutter multidex support enabled.
注: /Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/flutter_file_downloader-1.2.1/android/src/main/java/com/odehbros/flutter_file_downloader/permission/PermissionUtils.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/flutter_file_downloader-1.2.1/android/src/main/java/com/odehbros/flutter_file_downloader/MethodCallHandlerImpl.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by xiongzhaoxu** [comment] 2024-01-23 00:55
> I can't really get what the problem is!
> 
> is it related to deprecation warning?

Yes, hints about deprecation warnings

**Comment by abdallah-odeh** [comment] 2024-01-23 07:08
Duplicate of #8

**Closed by abdallah-odeh** 2024-01-23 07:08 UTC
